apiVersion: v1
kind: ServiceAccount
metadata:
  name: otelcol1
  namespace: otel-demo
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: openbao-csi-secrets
  namespace: otel-demo
rules:
- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["get", "create", "update", "patch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: openbao-csi-secrets
  namespace: otel-demo
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: openbao-csi-secrets
subjects:
- kind: ServiceAccount
  name: otelcol1
  namespace: otel-demo
