apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: openbao-certificates
  namespace: otel-demo
spec:
  provider: openbao
  parameters:
    vaultAddress: "http://openbao.openbao.svc.cluster.local:8200"
    vaultSkipTLSVerify: "true"
    vaultAuthMethod: "kubernetes"
    roleName: "otelcol1-role"
    objects: |
      - objectName: "certificate"
        secretPath: "certs/data/test1"
        secretKey: "certificate"
      - objectName: "private_key"
        secretPath: "certs/data/test1"
        secretKey: "private_key"
      - objectName: "ca_chain"
        secretPath: "certs/data/test1"
        secretKey: "ca_chain"
  secretObjects:
    - secretName: otelcol1-certs
      type: Opaque
      data:
        - objectName: certificate
          key: cert.crt
        - objectName: private_key
          key: cert.key
        - objectName: ca_chain
          key: ca.crt
