version: 2

updates:
  - package-ecosystem: "github-actions"
    directories:
      - "/.github/workflows"
    groups:
      ci:
        patterns:
          - "*"
    schedule:
      interval: "weekly"
      day: "sunday"

  - package-ecosystem: "gomod"
    directories:
      - "/src/*"
    groups:
      go:
        update-types: ["minor", "patch"]
    schedule:
      interval: "weekly"
      day: "sunday"

  - package-ecosystem: docker
    directories:
      - "/src/*"
    schedule:
      interval: "weekly"
      day: "sunday"
