version: 2

updates:

  - package-ecosystem: "github-actions"
    directory: "/"
    groups:
      ci:
        patterns:
          - "*"
    schedule:
      interval: "weekly"
      day: "sunday"

  - package-ecosystem: "gomod"
    directory: "/"
    groups:
      go:
        update-types:  ["minor","patch"]
    schedule:
      interval: "weekly"
      day: "sunday"

  - package-ecosystem: docker
    directory: "/"
    schedule:
      interval: "weekly"
      day: "sunday"
