version: '3'

description: Main Taskfile for managing the otel-audit-log-poc project. This file references other Taskfiles for specific functionalities.

includes:

  kind:
    desc: Manage Kind clusters (setup and teardown).
    taskfile: ./tasks/kind.yaml
    internal: true

  otel:
    desc: Port-forward the otel-demo frontend-proxy service to localhost:8080.
    taskfile: ./tasks/otel.yaml

  recommendation:
    desc: Builds the image of the recommendation service.
    taskfile: ./tasks/recommendation.yaml

tasks:

  default:
    desc: Install otel-demo in the local cluster.
    deps: [ otel:demo-install, otel:demo-status ]
    cmds:
      - task -a

  kube-context:
    desc: Set the kube-context to the local k3d cluster.
    deps:
      - task: otel:tools:install-kubectl
      - task: otel:cluster:merge-kubeconfig
    status:
      - '{{ .KUBECTL_CMD }} config current-context | grep -q k3d-otel-audit-log'
    cmds:
      - '{{ .KUBECTL_CMD }} config use-context k3d-otel-audit-log'
      - '{{ .KUBECTL_CMD }} config get-contexts'