version: "3"

description: Main Taskfile for managing the otel-audit-log-poc project. This file references other Taskfiles for specific functionalities.

includes:
  tools:
    desc: Install required tools (k3d, kubectl, kind).
    taskfile: ./tasks/tools.yaml

  kind:
    desc: Manage Kind clusters (setup and teardown).
    taskfile: ./tasks/kind.yaml

  k3d:
    desc: Manage Kind clusters (setup and teardown).
    taskfile: ./tasks/k3d.yaml
    aliases:
      - cluster

  istio:
    desc: Install and manage Istio in the local cluster.
    taskfile: ./tasks/istio.yaml

  otel-demo:
    desc: Port-forward the otel-demo frontend-proxy service to localhost:8080.
    taskfile: ./tasks/otel-demo.yaml

  dice:
    desc: Install and manage the dice applications (dice-go and dice-java).
    taskfile: ./tasks/dice.yaml

  e2e:
    desc: Run end-to-end tests.
    taskfile: ./tasks/e2e.yaml

  clients:
    desc: Builds the OTel clients - services in different languages.
    taskfile: ./tasks/clients.yaml

  go:
    desc: Build the go application.
    taskfile: ./tasks/go.yaml

  code:
    desc: Format all code files in the repository.
    taskfile: ./tasks/code.yaml

  misc:
    desc: Miscellaneous utility tasks.
    taskfile: ./tasks/misc.yaml

tasks:
  default:
    desc: Create and start local kubernetes cluster and install otel-demo.
    ignore_error: true
    deps:
      - task: cluster:start
    cmds:
      - task: otel:demo-status
      - task -a

  kube-context:
    desc: Set the kube-context to the local k3d cluster.
    deps:
      - task: tools:install-kubectl
      - task: k3d:merge-kubeconfig
    status:
      - "{{ .KUBECTL_CMD }} config current-context | grep -q k3d-otel-audit-log"
    cmds:
      - "{{ .KUBECTL_CMD }} config use-context k3d-otel-audit-log"
      - "{{ .KUBECTL_CMD }} config get-contexts"
