version: "3"

description: Taskfile with some Helm-related tasks.

includes:
  tools:
    taskfile: ./tools.yaml
    internal: true

tasks:
  create:
    desc: Build OCM transport archive from showroom descriptors.
    deps:
      - task: tools:install-ocm-v1
    requires:
      vars: [OCM_CMD]
    cmds:
      - "{{ .OCM_CMD }} version | jq"
      - |
        shopt -s nullglob
        FILES=(./showroom/ocm/*.yaml)
        if [[ ${#FILES[@]} -eq 0 ]]; then
          echo "No OCM descriptor files found under showroom/ocm/*.yaml"
          exit 1
        fi
        mkdir -p ./ocm
        rm -f ./ocm/transport.ctf
        {{ .OCM_CMD }} add componentversions --create --file ./ocm/transport.ctf "${FILES[@]}"
    silent: false
