exporters:
  debug:
    verbosity: detailed
  opensearch:
    http:
      endpoint: http://opensearch:9200
      tls:
        insecure: true
    logs_index: otel
    sending_queue:
      enabled: true # When disabled, the export happens immediately. If the receiver isn't available, the logs will be lost.
      queue_size: 10
      # block_on_queue_full: true  # not supported by opensearch exporter - https://github.com/hilmarf/opentelemetry-collector-contrib/tree/main/exporter/opensearchexporter
      storage: file_storage # Without storage, the queue is in memory and will be lost on restart.
      sizer: requests
      num_consumers: 1
    retry_on_failure:
      enabled: true
      max_elapsed_time: 0s # endless retries
      max_interval: 1s

extensions:
  health_check:
    endpoint: ${env:MY_POD_IP}:13133
  file_storage:
    directory: /tmp/collector-volume
    create_directory: true
processors:
  memory_limiter:
    check_interval: 5s
    limit_percentage: 80
    spike_limit_percentage: 25
  resource:
    attributes:
      - action: insert
        from_attribute: k8s.pod.uid
        key: service.instance.id
  transform:
    error_mode: ignore
    trace_statements:
      - context: span
        statements:
          - replace_pattern(name, "\\?.*", "")
          - replace_match(name, "GET /api/products/*", "GET /api/products/{productId}")
receivers:
  otlp:
    protocols:
      grpc:
        endpoint: ${env:MY_POD_IP}:4317
      http:
        cors:
          allowed_origins:
            - http://*
            - https://*
        endpoint: ${env:MY_POD_IP}:4318
service:
  extensions:
    - health_check
    - file_storage
  pipelines:
    logs:
      receivers:
        - otlp
      processors:
        - memory_limiter
        - resource
      exporters:
        - opensearch
        - debug
#    metrics:
#      receivers:
#      - otlp
#      processors:
#      - memory_limiter
#      - resource
#      exporters:
#      - debug
