version: "3"

description: This file defines the tasks for code formatting across various languages in the repository.

vars:
  SPELLCHECK_ON: md,txt,html

tasks:
  format:
    desc: Format all code files in the repository
    cmds:
      - npx --yes prettier --write '**/*.{js,ts,jsx,tsx,css,scss,md,yml,yaml,json}' || true
      - npx --yes markdownlint-cli2 '**/*.md' --config .github/config/.markdownlint.json --fix || true
      - "[ -d src ] && gofmt -w src || true"
      - '[ -d src ] && find src -name "*.java" -exec java -jar google-java-format.jar --replace {} + || true'
      - '[ -d src ] && find src -name "*.go" -exec gofmt -w {} + || true'
    silent: false

  lint:
    desc: Lint all code and markdown files in the repository
    cmds:
      - "npx --yes prettier --check '**/*.{js,ts,jsx,tsx,css,scss,md,yml,yaml,json}' || (echo '❌ Prettier check failed! Please format your code with: task code:format' && exit 1)"
      - npx --yes markdownlint-cli2 '**/*.md' --config .github/config/.markdownlint.json || (echo "❌ Markdownlint check failed! Please fix Markdown issues." && exit 1)
    silent: false

  spellcheck:
    desc: Spell check all markdown, text, and HTML files in the repository
    cmds:
      - npx --yes cspell --config .github/config/cspell.json '**/*.{ {{.SPELLCHECK_ON}} }' --unique --no-progress
    silent: false

  dictionary:
    desc: Update the dictionary for spell checking
    vars:
      DICTIONARY: .github/config/dictionary.txt
      CSPELL_CONFIG: .github/config/cspell.json
    cmds:
      - npx --yes cspell --config {{.CSPELL_CONFIG}} '**/*.{ {{.SPELLCHECK_ON}} }' --words-only --unique --no-progress --no-summary
        | tr '[:upper:]' '[:lower:]'
        | cat - {{.DICTIONARY}}
        | sort -u > {{.DICTIONARY}}
      - echo "Dictionary updated at {{.DICTIONARY}}"
    silent: true
