version: "3"

description: This file defines the tasks for code formatting across various languages in the repository.

tasks:
  format:
    desc: Format all code files in the repository
    cmds:
      - npx --yes prettier --write '**/*.{js,ts,jsx,tsx,css,scss,md,yml,yaml,json}' || true
      - "[ -d src ] && gofmt -w src || true"
      - '[ -d src ] && find src -name "*.java" -exec java -jar google-java-format.jar --replace {} + || true'
      - '[ -d src ] && find src -name "*.go" -exec gofmt -w {} + || true'
    silent: false
