version: "3"

description: Taskfile for running end-to-end tests.

vars:
  E2E_NS: "e2e"
  LOG_SINK_PORT: "30080"
  MAX_COUNTER: "100"

includes:
  misc:
    desc: Miscellaneous utility tasks.
    taskfile: ./misc.yaml
    internal: true

  tools:
    desc: Install required tools.
    taskfile: ./tools.yaml
    internal: true

tasks:
  install:
    desc: Install all required components for end-to-end testing.
    run: once
    deps:
      - task: tools:install-kubectl
      - task: create-namespace
    requires:
      vars: [KUBECTL_CMD, E2E_NS]
    preconditions:
      - sh: "{{ .KUBECTL_CMD }} cluster-info >/dev/null 2>&1"
        msg: "Please ensure that you have a k8s-cluster running. Try:\ttask cluster:start"
    cmds:
      - "{{ .KUBECTL_CMD }} apply -f kubectl/log-sink.yaml -n {{ .E2E_NS }}"
      - "{{ .KUBECTL_CMD }} rollout status deployment/log-sink -n {{ .E2E_NS }} --timeout=120s"
      - "{{ .KUBECTL_CMD }} apply -f kubectl/collector.yaml -n {{ .E2E_NS }}"
      - "{{ .KUBECTL_CMD }} rollout status deployment/collector -n {{ .E2E_NS }} --timeout=120s"

  create-namespace:
    desc: Create the e2e namespace if it doesn't exist.
    requires:
      vars: [KUBECTL_CMD, E2E_NS]
    status:
      - "{{ .KUBECTL_CMD }} get ns {{ .E2E_NS }} >/dev/null 2>&1"
    cmds:
      - "{{ .KUBECTL_CMD }} create ns {{ .E2E_NS }} --dry-run=client -o yaml | {{ .KUBECTL_CMD }} apply -f -"

  run:
    desc: Run the loggen Job for end-to-end testing (can be run repeatedly)
    requires:
      vars: [KUBECTL_CMD, E2E_NS]
    cmds:
      - "{{ .KUBECTL_CMD }} delete job loggen-go -n {{ .E2E_NS }} --ignore-not-found"
      - "{{ .KUBECTL_CMD }} apply -f kubectl/loggen-go.yaml -n {{ .E2E_NS }}"
      - "{{ .KUBECTL_CMD }} wait --for=condition=complete --timeout=120s job/loggen-go -n {{ .E2E_NS }}"

  uninstall:
    desc: Uninstall all components deployed for end-to-end testing.
    run: once
    deps:
      - task: tools:install-kubectl
    requires:
      vars: [KUBECTL_CMD, E2E_NS]
    preconditions:
      - sh: "{{ .KUBECTL_CMD }} cluster-info >/dev/null 2>&1"
        msg: "Please ensure that you have a k8s-cluster running. Try:\ttask cluster:start"
    cmds:
      - "{{ .KUBECTL_CMD }} delete ns {{ .E2E_NS }} --ignore-not-found"

  verify:
    desc: Retrieve received logs from log-sink and query for missing counters.
    deps:
      - task: misc:create-work-dir
    requires:
      vars: [KUBECTL_CMD, WORK_DIR, E2E_NS, LOG_SINK_PORT, MAX_COUNTER]
    preconditions:
      - sh: "{{ .KUBECTL_CMD }} cluster-info >/dev/null 2>&1"
        msg: "Please ensure that you have a k8s-cluster running. Try:\ttask cluster:start"
    cmds:
      - |
        curl -s http://localhost:{{ .LOG_SINK_PORT }}/received_logs.json > {{ .WORK_DIR }}/received_logs.json
        echo "Printing missing counters:"
        comm -23 <(seq 1 {{ .MAX_COUNTER }}) <(jq -r '.resourceLogs[].scopeLogs[].logRecords[].attributes[] | select(.key=="log-count") | .value.stringValue' {{ .WORK_DIR }}/received_logs.json | sort -n | uniq)
