version: "3"

description: Taskfile for running end-to-end tests.

vars:
  E2E_NS: "e2e"

includes:
  tools:
    desc: Install required tools.
    taskfile: ./tools.yaml
    internal: true

tasks:
  install:
    desc: Install all required components for end-to-end testing.
    run: once
    deps:
      - task: tools:install-kubectl
      - task: create-namespace
    requires:
      vars: [KUBECTL_CMD, E2E_NS]
    preconditions:
      - sh: "{{ .KUBECTL_CMD }} cluster-info >/dev/null 2>&1"
        msg: "Please ensure that you have a k8s-cluster running. Try:\ttask cluster:start"
    cmds:
      - "{{ .KUBECTL_CMD }} apply -f kubectl/log-sink.yaml -n {{ .E2E_NS }}"
      - "{{ .KUBECTL_CMD }} rollout status deployment/log-sink -n {{ .E2E_NS }} --timeout=120s"
      - "{{ .KUBECTL_CMD }} apply -f kubectl/collector.yaml -n {{ .E2E_NS }}"
      - "{{ .KUBECTL_CMD }} rollout status deployment/collector -n {{ .E2E_NS }} --timeout=120s"
      - "{{ .KUBECTL_CMD }} apply -f kubectl/loggen-go.yaml -n {{ .E2E_NS }}"

  create-namespace:
    desc: Create the e2e namespace if it doesn't exist.
    requires:
      vars: [KUBECTL_CMD, E2E_NS]
    status:
      - "{{ .KUBECTL_CMD }} get ns {{ .E2E_NS }} >/dev/null 2>&1"
    cmds:
      - "{{ .KUBECTL_CMD }} create ns {{ .E2E_NS }} --dry-run=client -o yaml | {{ .KUBECTL_CMD }} apply -f -"

  uninstall:
    desc: Uninstall all components deployed for end-to-end testing.
    run: once
    deps:
      - task: tools:install-kubectl
    requires:
      vars: [KUBECTL_CMD, E2E_NS]
    preconditions:
      - sh: "{{ .KUBECTL_CMD }} cluster-info >/dev/null 2>&1"
        msg: "Please ensure that you have a k8s-cluster running. Try:\ttask cluster:start"
    cmds:
      - "{{ .KUBECTL_CMD }} delete ns {{ .E2E_NS }} --ignore-not-found"
