version: '3'

description: Taskfile to build our custom services and deploy them to a local Kind cluster.

vars:
  BUILD_CMD:
    sh: |
      if command -v docker >/dev/null 2>&1; then
        command -v docker
      elif command -v podman >/dev/null 2>&1; then
        command -v podman
      fi
  CONTAINER_CMD:
    sh: |
      if echo "{{ .BUILD_CMD }}" | grep -q podman; then
        echo "podman"
      else
        echo "docker"
      fi

tasks:

  build:
    desc: Builds the image of the recommendation service.
    platforms: [ linux, darwin ]
    cmds:
    - '{{ .BUILD_CMD }} build --file src/recommendation/Dockerfile --tag otel-recommendation src/recommendation/ {{if eq .CONTAINER_CMD "podman" }} --env RECOMMENDATION_PORT=8080 {{ end }}'

  push:
    desc: Push the built recommendation image to ghcr.io/apeirora/audit-log-poc-for-otel.
    platforms: [ linux, darwin ]
    deps:
    - build
    cmds:
    - '{{ .BUILD_CMD }} tag otel-recommendation ghcr.io/apeirora/audit-log-poc-for-otel/recommendation:latest'
    - '{{ .BUILD_CMD }} push ghcr.io/apeirora/audit-log-poc-for-otel/recommendation:latest'
