spring:
  application:
    name: dice-java
  task:
    execution:
      pool:
        core-size: 2
        max-size: 5
    scheduling:
      pool:
        size: 2

server:
  address: 0.0.0.0
  port: 8082

management:
  metrics:
    export:
      enabled: false
      otlp:
        endpoint: http://172.19.0.2:30318
  otlp:
    metrics:
      export:
        enabled: false

otel:
  exporter:
    otlp:
      endpoint: http://172.19.0.2:30318
      logs:
        endpoint: http://172.19.0.2:30318/v1/logs
