# Deploy `dice-java` with a per-pod OpenTelemetry Collector sidecar using on-node file storage
# - Deployment with 3 replicas
# - Each pod runs the application container and an otelcol sidecar
# - Sidecar uses hostPath volume `/var/lib/otelcol/storage` with subPathExpr to create per-pod directories
# - ConfigMap contains the otelcol config that uses file_storage

apiVersion: v1
kind: ConfigMap
metadata:
  name: dice-java-otelcol-config
  namespace: default
data:
  config.yaml: |
    extensions:
      file_storage:
        directory: /var/lib/otelcol/storage
        create_directory: true
      health_check:
        endpoint: ${env:MY_POD_IP}:13133

    receivers:
      otlp:
        protocols:
          grpc:
            endpoint: 0.0.0.0:4317
          http:
            endpoint: 0.0.0.0:4318

    processors:
      batch:
        send_batch_size: 1024
        timeout: 5s
      memory_limiter:
        check_interval: 5s
        limit_percentage: 80
        spike_limit_percentage: 25

    exporters:
      otlp:
        endpoint: log-sink:4317
        tls:
          insecure: true
        sending_queue:
          enabled: true
          storage: file_storage
        retry_on_failure:
          enabled: true
          max_elapsed_time: 0s

      debug: {}

    service:
      extensions: [file_storage, health_check]
      pipelines:
        logs:
          receivers: [otlp]
          processors: [batch, memory_limiter]
          exporters: [otlp, debug]
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: dice-java
  labels:
    app: dice-java
spec:
  replicas: 3
  selector:
    matchLabels:
      app: dice-java
  template:
    metadata:
      labels:
        app: dice-java
    spec:
      # Allow the pod to read its own IP via downward API
      containers:
        - name: dice-java
          image: ghcr.io/apeirora/audit-log-poc-for-otel/dice-java:latest
          imagePullPolicy: IfNotPresent
          env:
            - name: REST_PORT
              value: "8082"
            # application should send OTLP to the sidecar on localhost
            - name: OTEL_EXPORTER_OTLP_ENDPOINT_GRPC
              value: "http://127.0.0.1:4317"
            - name: OTEL_EXPORTER_OTLP_ENDPOINT_HTTP
              value: "http://127.0.0.1:4318"
            - name: OTEL_EXPORTER_OTLP_INSECURE
              value: "true"
          ports:
            - containerPort: 8082
          resources:
            limits:
              memory: 256Mi
              cpu: 200m
            requests:
              memory: 128Mi
              cpu: 100m
        - name: otel-collector
          image: otel/opentelemetry-collector-contrib:0.133.0
          args:
            - "--config=/etc/otelcol-contrib/config.yaml"
          env:
            - name: MY_POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
            - name: MY_POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
          ports:
            - name: otlp-grpc
              containerPort: 4317
              protocol: TCP
            - name: otlp-http
              containerPort: 4318
              protocol: TCP
            - name: health
              containerPort: 13133
              protocol: TCP
          volumeMounts:
            - name: otelcol-config
              mountPath: /etc/otelcol-contrib
              readOnly: true
            - name: otelcol-storage
              mountPath: /var/lib/otelcol/storage
              # subPathExpr isolates storage per pod (requires k8s v1.17+)
              subPathExpr: "$(MY_POD_NAME)"
          livenessProbe:
            httpGet:
              path: /
              port: 13133
            initialDelaySeconds: 15
            periodSeconds: 20
            timeoutSeconds: 3
          readinessProbe:
            httpGet:
              path: /
              port: 13133
            initialDelaySeconds: 5
            periodSeconds: 10
            timeoutSeconds: 3
          securityContext:
            runAsUser: 10001
            runAsGroup: 0
            runAsNonRoot: true
      volumes:
        - name: otelcol-config
          configMap:
            name: dice-java-otelcol-config
            items:
              - key: config.yaml
                path: config.yaml
        - name: otelcol-storage
          hostPath:
            path: /var/lib/otelcol/storage
            type: DirectoryOrCreate
---
apiVersion: v1
kind: Service
metadata:
  name: dice-java
  labels:
    app: dice-java
spec:
  selector:
    app: dice-java
  ports:
    - protocol: TCP
      port: 8082
      targetPort: 8082
  type: ClusterIP
