# Deploy `dice-java` with a per-pod OpenTelemetry Collector sidecar
# - Deployment with 3 replicas
# - Each pod runs the application container and an otelcol sidecar
# - ConfigMap contains the otelcol config

apiVersion: v1
kind: ConfigMap
metadata:
  name: dice-java-otelcol-config
data:
  config.yaml: |
    receivers:
      otlp:
        protocols:
          grpc:
            endpoint: 0.0.0.0:4317
          http:
            endpoint: 0.0.0.0:4318

    processors:
      batch: # used to optimize export calls in all pipelines
        send_batch_size: 1024
        timeout: 5s

    exporters:
      otlp:
        endpoint: log-sink.tier-3.svc.cluster.local:4317
        tls:
          insecure: true
      debug:

    service:
      pipelines:
        logs:
          receivers: [otlp]
          processors: [batch]
          exporters: [otlp, debug]
        metrics:
          receivers: [otlp]
          processors: [batch]
          exporters: [otlp, debug]
        traces:
          receivers: [otlp]
          processors: [batch]
          exporters: [otlp, debug]
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: dice-java
  labels:
    app: dice-java
spec:
  replicas: 2
  selector:
    matchLabels:
      app: dice-java
  template:
    metadata:
      labels:
        app: dice-java
    spec:
      containers:
        - name: dice-java
          image: ghcr.io/apeirora/audit-log-poc-for-otel/dice-java:latest
          imagePullPolicy: IfNotPresent
          env:
            - name: REST_PORT
              value: "8082"
            # application should send OTLP to the sidecar on localhost
            - name: OTEL_EXPORTER_OTLP_ENDPOINT_GRPC
              value: "http://127.0.0.1:4317"
            - name: OTEL_EXPORTER_OTLP_ENDPOINT_HTTP
              value: "http://127.0.0.1:4318"
            - name: OTEL_EXPORTER_OTLP_INSECURE
              value: "true"
          ports:
            - containerPort: 8082
          resources:
            limits:
              memory: 256Mi
              cpu: 200m
            requests:
              memory: 128Mi
              cpu: 100m
        - name: otel-collector
          image: otel/opentelemetry-collector-contrib:latest
          imagePullPolicy: Always
          args:
            # see ConfigMap mapped as volume below
            - "--config=/etc/otelcol-contrib/config.yaml"
          ports:
            - name: otlp-grpc
              containerPort: 4317
              protocol: TCP
            - name: otlp-http
              containerPort: 4318
              protocol: TCP
          volumeMounts:
            - name: otelcol-config
              mountPath: /etc/otelcol-contrib
              readOnly: true
      volumes:
        - name: otelcol-config
          configMap:
            name: dice-java-otelcol-config
            items:
              - key: config.yaml
                path: config.yaml
---
apiVersion: v1
kind: Service
metadata:
  name: dice-java
  labels:
    app: dice-java
spec:
  selector:
    app: dice-java
  ports:
    - protocol: TCP
      port: 8082
      targetPort: 8082
  type: ClusterIP
