apiVersion: v1
kind: ConfigMap
metadata:
  name: collector-config
  namespace: otel-demo
data:
  config.yaml: |
    receivers:
      otlp:
        protocols:
          grpc:
            endpoint: 0.0.0.0:4317
          http:
            endpoint: 0.0.0.0:4318
    exporters:
      otlp:
        endpoint: log-sink:4317
        tls:
          insecure: true
    extensions:
      health_check:
        endpoint: ${env:MY_POD_IP}:13133
    service:
      extensions:
      pipelines:
        logs:
          receivers: [otlp]
          processors: []
          exporters: [otlp]
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: collector
  namespace: otel-demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: collector
  template:
    metadata:
      labels:
        app: collector
    spec:
      containers:
        - name: collector
          # image: otel/opentelemetry-collector:latest  # contains only [zpages, health_check, pprof] extensions
          image: otel/opentelemetry-collector-contrib:latest
          args: ["--config=/conf/config.yaml"]
          volumeMounts:
            - name: config
              mountPath: /conf
      volumes:
        - name: config
          configMap:
            name: collector-config
---
apiVersion: v1
kind: Service
metadata:
  name: collector
  namespace: otel-demo
spec:
  selector:
    app: collector
  ports:
    - name: grpc
      port: 4317
      targetPort: 4317
    - name: http
      port: 4318
      targetPort: 4318
