apiVersion: apps/v1
kind: Deployment
metadata:
  name: dice-java
  namespace: otel-demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dice-java
  template:
    metadata:
      labels:
        app: dice-java
    spec:
      containers:
        - name: dice-java
          image: ghcr.io/apeirora/audit-log-poc-for-otel/dice-java:latest
          imagePullPolicy: IfNotPresent
          env:
            - name: REST_PORT
              value: "8082"
            - name: OTEL_EXPORTER_OTLP_ENDPOINT_GRPC
              value: "http://otel-collector:4317"
            - name: OTEL_EXPORTER_OTLP_ENDPOINT_HTTP
              value: "http://otel-collector:4318"
          ports:
            - containerPort: 8082
---
apiVersion: v1
kind: Service
metadata:
  name: dice-java
  namespace: otel-demo
spec:
  selector:
    app: dice-java
  ports:
    - protocol: TCP
      port: 8082
      targetPort: 8082
      nodePort: 30382
  type: NodePort
