apiVersion: batch/v1
kind: Job
metadata:
  name: loggen-go
  labels:
    app: loggen-go
spec:
  template:
    spec:
      containers:
        - name: loggen-go
          image: ghcr.io/apeirora/audit-log-poc-for-otel/loggen-go:latest
          imagePullPolicy: Always
          env:
            - name: OTEL_EXPORTER_OTLP_LOGS_ENDPOINT
              value: "http://otel-collector:4317"
            - name: OTEL_EXPORTER_OTLP_INSECURE
              value: "true"
          resources:
            limits:
              cpu: 100m
              memory: 64Mi
            requests:
              cpu: 50m
              memory: 32Mi
      restartPolicy: OnFailure
