alternateConfig:
  receivers:
    otlp:
      protocols:
        grpc:
          endpoint: 0.0.0.0:4317
        http:
          endpoint: 0.0.0.0:4318
  exporters:
    debug:
      verbosity: detailed
  extensions:
    health_check:
      endpoint: ${env:MY_POD_IP}:13133
  service:
    extensions:
      - health_check
    pipelines:
      logs:
        receivers:
          - otlp
        exporters:
          - debug
resources:
  limits:
    memory: 512Mi
  requests:
    memory: 256Mi
image:
  repository: otel/opentelemetry-collector-k8s
  tag: latest
mode: deployment
