grafana.ini:
  auth.anonymous:
    enabled: true
    org_name: Main Org.
    org_role: Admin

datasources:
  datasources.yaml:
    apiVersion: 1
    datasources:
      - name: Prometheus
        type: prometheus
        uid: prometheus
        url: http://prometheus-server
        access: proxy
        isDefault: true
        editable: true
        jsonData:
          httpMethod: POST
          timeInterval: 15s
          queryTimeout: 60s
