name: Lint code

on:
  pull_request:
    paths:
      - "**/*.md"
      - "**/*.json"
      - "**/*.yaml"
      - "**/*.yml"
      - "**/*.go"
      - "**/*.java"
  push:
    branches: [main]
    paths:
      - "**/*.md"
      - "**/*.json"
      - "**/*.yaml"
      - "**/*.yml"
      - "**/*.go"
      - "**/*.java"

jobs:
  code-lint:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Install Task
        uses: arduino/setup-task@c0bc642852239c2689f73f4ea6459c29405f3c52 # v3.0.0
        with:
          version: 3.x
          repo-token: ${{ secrets.GITHUB_TOKEN }}
      - name: Checkout Code
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
      - name: Do some linting
        run: task code:lint
