name: build and push loggen-go

on:
  push:
    branches:
      - main
    paths:
      - "src/loggen-go/**"

jobs:
  # test locally with: `act -s GITHUB_TOKEN=$(gh auth token) --env github.actor=$USER`
  # get 'act': https://nektosact.com/installation/index.html
  build-and-push-loggen-go:
    name: Build and Push
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Install Task
        uses: arduino/setup-task@b91d5d2c96a56797b48ac1e0e89220bf64044611 # v2.0.0
        with:
          version: 3.x
          repo-token: ${{ secrets.GITHUB_TOKEN }}
      - name: Checkout Code
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
      - name: Build image
        run: task clients:build-loggen-go
      - name: Login to GitHub Container Registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin
      - name: Push to registry
        run: task clients:push-loggen-go
