name: Recommendation

on:
  push:
    branches:
      - main
    paths:
      - "src/recommendation/**"

jobs:
  # test locally with: `act -s GITHUB_TOKEN=$(gh auth token) --env github.actor=$USER`
  # get 'act': https://nektosact.com/installation/index.html
  build-and-push-recommendation:
    name: Build and Push
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Install Task
        uses: arduino/setup-task@24c5e13bce349197642746563945fcdf9355e8f4 # v2.0.0
        with:
          version: 3.x
          repo-token: ${{ secrets.GITHUB_TOKEN }}
      - name: Checkout Code
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - name: Build `recommendation` image
        run: task recommendation:build
      - name: Login to GitHub Container Registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin
      - name: Push `recommendation` to registry
        run: task recommendation:push
